openapi: 3.1.0
x-stoplight:
  id: u8zv5k21qblp1
info:
  title: api
  version: '1.0'
  summary: apiiii
  description: |-
    cnv cv 
    xvghh
    fghj
    fgdhyfhfhf dtgdhyh
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userId}':
    parameters:
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: string
        name: userId
        in: path
        required: true
      - schema:
          type: integer
        name: userId
        in: path
        required: true
        description: Id of an existing user.
    get:
      summary: Get User Info by User ID
      tags: []
      responses:
        '200':
          description: User Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Get User Alice Smith:
                  value:
                    id: 142
                    firstName: Alice
                    lastName: Smith
                    email: alice.smith@gmail.com
                    dateOfBirth: '1997-10-31'
                    emailVerified: true
                    signUpDate: '2019-08-24'
        '404':
          description: User Not Found
      operationId: get-users-userId
      description: Retrieve the information of the user with the matching user ID.
      x-stoplight:
        id: y79afh4ja2zo1
    patch:
      summary: Update User Information
      operationId: patch-users-userId
      responses:
        '200':
          description: User Updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                Updated User Rebecca Baker:
                  value:
                    id: 13
                    firstName: Rebecca
                    lastName: Baker
                    email: rebecca@gmail.com
                    dateOfBirth: '1985-10-02'
                    emailVerified: false
                    createDate: '2019-08-24'
        '404':
          description: User Not Found
        '409':
          description: Email Already Taken
      description: Update the information of an existing user.
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                  description: 'If a new email is given, the user''s email verified property will be set to false.'
                dateOfBirth:
                  type: string
            examples:
              Update First Name:
                value:
                  firstName: Rebecca
              Update Email:
                value:
                  email: rebecca@gmail.com
              Update Last Name & Date of Birth:
                value:
                  lastName: Baker
                  dateOfBirth: '1985-10-02'
        description: Patch user properties to update.
      x-stoplight:
        id: ukl5wgqxdbwvx
    post:
      summary: Your POST endpoint
      tags: []
      responses: {}
      operationId: post-users-userId
      x-stoplight:
        id: mhbwnuj5unxjz
    delete:
      summary: Your DELETE endpoint
      tags: []
      responses: {}
      operationId: delete-users-userId
      x-stoplight:
        id: 0ot37qc7mls9x
    options:
      summary: Your OPTIONS endpoint
      tags: []
      responses: {}
      operationId: options-users-userId
      x-stoplight:
        id: nrqbo46tedvfy
  /user:
    post:
      summary: Create New User
      operationId: post-user
      responses:
        '200':
          description: User Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              examples:
                New User Bob Fellow:
                  value:
                    id: 12
                    firstName: Bob
                    lastName: Fellow
                    email: bob.fellow@gmail.com
                    dateOfBirth: '1996-08-24'
                    emailVerified: false
                    createDate: '2020-11-18'
        '400':
          description: Missing Required Information
        '409':
          description: Email Already Taken
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                firstName:
                  type: string
                lastName:
                  type: string
                email:
                  type: string
                dateOfBirth:
                  type: string
                  format: date
              required:
                - firstName
                - lastName
                - email
                - dateOfBirth
            examples:
              Create User Bob Fellow:
                value:
                  firstName: Bob
                  lastName: Fellow
                  email: bob.fellow@gmail.com
                  dateOfBirth: '1996-08-24'
        description: Post the necessary fields for the API to create a new user.
      description: Create a new user.
      x-stoplight:
        id: m35b9v7r0my9z
components:
  schemas:
    User:
      title: User
      type: object
      description: ''
      examples:
        - id: 142
          firstName: Alice
          lastName: Smith
          email: alice.smith@gmail.com
          dateOfBirth: '1997-10-31'
          emailVerified: true
          signUpDate: '2019-08-24'
      properties:
        id:
          type: integer
          description: Unique identifier for the given user.
          x-stoplight:
            id: 6bw20t9vwix62
        firstName:
          type: string
          x-stoplight:
            id: c727i2up8vi6t
        lastName:
          type: string
          x-stoplight:
            id: 3mtvsjd2lqk1m
        email:
          type: string
          format: email
          x-stoplight:
            id: cev55hs4nmhjr
        dateOfBirth:
          type: string
          format: date
          example: '1997-10-31'
          x-stoplight:
            id: enyaxxegrfy4u
        emailVerified:
          type: boolean
          description: Set to true if the user's email has been verified.
          x-stoplight:
            id: ma7iffwm8lfef
        createDate:
          type: string
          format: date
          description: The date that the user was created.
          x-stoplight:
            id: 3efwlc42t2231
      required:
        - id
        - firstName
        - lastName
        - email
        - emailVerified
      x-stoplight:
        id: hoyujuson3932
    dfhgujhigj:
      title: dfhgujhigj
      x-stoplight:
        id: ehhg5ojuqeo23
      type: object
      properties:
        id:
          type: string
          x-stoplight:
            id: 54bb5mbbsbn7c
        edrff:
          type: string
          x-stoplight:
            id: 37pod9cs1nyxe
      description: edrftegrg
      x-internal: true
x-internal: true
